public class PrintEven { public static void main(String[] args){
int limit, i; //create a scanner object to get the input.
Scanner in = new Scanner(System. in); ...
System. out. ...
//print the even numbers. System. ...
//loop till the limit. for(i=1; i<=limit; i++){
//divide by 2 if remainder is 0 then it is an even number. ...
}
